### ISSUE TITLE
API Key Entry Misleading

### ISSUE THREAD

**Issue by AbandonedCart** [endrl/segment-editor#11]
It's really just personal opinion, but the fact that clicking on the API key fills in a generic "example" is a bit misleading. 

When the screen loads, it is blank, so I went and copied the key. When returning to the entry and clicking it, it seems to fill it in. 

It's a generic example, but that isn't immediately obvious. After all, not many people read their keys when copying them or really read them again after pasting. It can easily be mistaken for the app grabbing the key from the clipboard.

**Comment by Gaffers2277** [comment]
I second this, just had the same issue. I thought it was already filled and it kept telling me it was an invalid api key, which doesn't tell me it was just blank.

**Comment by endrl** [comment]
Removed it for the latest release, thank you for your feedback

**Comment by AbandonedCart** [comment]
Thanks!
