### ISSUE TITLE
Jellyfin Server with Media Segments API docker crashes

### ISSUE THREAD

**Issue by binarygeek119** [endrl/segment-editor#2]
i get the crash over and over again.

new to jellyfin coming from emby.

started fresh and after a little while some crashes and the server needs a restart.

logs
had to upload to 3 party site sore size limites
https://tmpfiles.org/3101106/log_20231105_001.log
https://tmpfiles.org/3101123/log_20231106_001.log
https://tmpfiles.org/3101122/log_20231106.log

**Comment by endrl** [comment]
Hello and sorry for the late reply. Did you try to run that on arm64 based OS? Sadly the logs are offline.
If you are new to Jellyfin i recommend to use https://github.com/jumoog/intro-skipper
