### ISSUE TITLE
Why is a custom Jellyfin Image needed?

### ISSUE THREAD

**Issue by BLACK4585** [endrl/segment-editor#3]
Hello, I just installed this project on a second environment to test it. And I really like the idea of the graphical segment editor!
But why is a custom Jellyfin Image needed? [This](https://github.com/jumoog/intro-skipper) intro skipper also seems to add some API endpoints and just work as a plugin.

**Comment by endrl** [comment]
Hello @BLACK4585,
my target is to add official Intro/Outro support to Jellyfin. All current solutions apply different patches to jellyfin, some clients support that and some don't. The editor is therefore just a side project of this idea, i use(d) it to test my new api.

**Comment by BLACK4585** [comment]
So this whole project is more just for testing purposes, and we can wait for PRs in the Jellyfin Repo in the future? 👀

**Comment by endrl** [comment]
The foundation of this editor (and everything else) is a server side official api. https://github.com/jellyfin/jellyfin/pull/10530

**Comment by foux** [comment]
@endrl do you intend of finishing https://github.com/jellyfin/jellyfin/pull/10530 ? Otherwise you perhaps might hand it over to someone else?

**Comment by endrl** [comment]
The custom image is no longer in use. See latest Readme
