### ISSUE TITLE
Episode and Shows sorting is all over the place

### ISSUE THREAD

**Issue by mihawk90** [endrl/segment-editor#9]
Now that 10.10 is finally out, I actually get to look at this properly :sweat_smile: 

First thing that struck me what the the episodes in a season list are seemingly random. Looking at the Dev Tools network tab, it seems to just be the order JF returns the items in, and the UI just dumps them one by one.

This can be fixed by appending `&sortBy=AiredEpisodeOrder` to the query for a season.

The same is true for the shows themselves, where the fix would be a `&sortBy=SortName`.

I briefly looked into the code, and it seems the query is made here:
https://github.com/endrl/segment-editor/blob/0e623dd61e185abb7b5e933d6ebec33f512030b4/src/composables/api.ts#L31-L35

I thought it might be an easy fix just appending the parameter, but seeing as this seems to be a rather generic function, I don't think it's that simple.

I guess the parameter could be provided as `&sortBy=AiredEpisodeOrder,SortName`, which seems to return the same order as the standalone sort-orders.

I'm just know sure whether that would interfere with any other functionality.

**Comment by endrl** [comment]
Thank you for your report, i added it to the latest release. Just report back if it works for you.
